search_keywords = [
    "fedex",
    "USPS",
    "UPS",
    "parcel shipping",
    "DHL",
    "shipping delays",
    "package tracking",
    "best shipping carriers",
    "parcel tracking issues",
    "lost package help",
    "shipping delays",
    "UPS vs FedEx",
    "best courier services",
    "international shipping problems",
    "parcel insurance claims",
    "how to track lost package",
    "FedEx delivery reviews",
    "shipping cost calculator",
    "best way to ship fragile items",
    "FedEx lost package",
    "UPS shipping reviews",
    "shipping company reviews",
    "parcel delivery services",
    "best shipping options",
    "how to find lost parcel",
    "delivery service ratings",
    "international parcel shipping",
    "postal service complaints",
    "why is my package delayed",
    "FedEx vs DHL",
    "cheapest way to ship packages",
    "shipping rates comparison",
    "package not delivered",
    "courier service recommendations",
    "customs clearance delay",
    "shipping company feedback",
    "how to file lost package claim",
    "DHL lost package",
    "Yelp shipping reviews",
    "best shipping services Reddit",
    "Reddit shipping delays",
    "lost parcel claim process",
    "how to get refund for lost package",
    "best USPS alternatives",
    "shipping fees discussion",
    "international shipping cost",
    "Amazon package not delivered",
    "shipping industry trends",
    "local courier reviews",
    "FedEx or UPS which is better",
    "shipping carrier delays",
    "how to prevent lost packages",
    "FedEx vs USPS shipping times",
    "how to track international parcel",
    "Reddit shipping complaints",
    "most reliable delivery services",
    "how to report lost package",
    "delivery delay updates",
    "best ways to ship electronics",
    "package not showing up in tracking",
    "parcel delivery feedback",
    "Reddit international shipping advice",
    "shipping cost increase 2023",
    "DHL or UPS for international shipping",
    "USPS package not delivered",
    "reviews on shipping carriers",
    "Instagram shipping complaints",
    "best way to package fragile items",
    "shipping services RSS feed",
    "cheapest way to ship heavy items",
    "how to insure valuable packages",
    "shipping cost vs speed",
    "shipping feedback Reddit",
    "news on shipping delays",
    "Reddit shipping company reviews",
    "how to reduce shipping costs",
    "FedEx vs DHL international shipping",
    "tracking number not working",
    "Instagram parcel shipping tips",
    "best international shipping carriers",
    "how to expedite shipping",
    "package stuck in customs Reddit",
    "DHL or FedEx for international shipping",
    "news on parcel delivery industry",
    "why is international shipping so slow",
    "Facebook shipping delays",
    "how to handle missing packages",
    "Reddit package insurance advice",
    "why is my package stuck",
    "fastest way to ship parcels",
    "how to track FedEx package",
    "UPS shipping rates comparison",
    "shipping carriers Reddit review",
    "FedEx vs UPS cost",
    "Reddit parcel delivery stories",
    "international shipping rates Reddit",
    "FedEx vs USPS for small packages",
    "shipping insurance Reddit",
    "Facebook lost package help",
    "DHL vs USPS international",
    "best shipping company for businesses",
    "Reddit carrier shipping stories",
    "Yelp FedEx reviews",
    "Yelp UPS reviews",
    "cheap parcel shipping Reddit",
    "how to ship perishable items",
    "Amazon vs FedEx delivery times",
    "lost package Reddit stories",
    "USPS slow delivery Reddit",
    "Instagram FedEx complaints",
    "Reddit best shipping insurance",
    "tracking package updates",
    "shipping discussions Reddit",
    "package damaged in shipping",
    "parcel delivery stories Reddit",
    "best courier service for fragile items",
    "FedEx slow shipping Reddit",
    "Facebook lost package complaints",
    "how to track DHL package",
    "why are shipping times so long",
    "news on shipping rates",
    "why is FedEx always late",
    "Facebook shipping group discussions",
    "Reddit shipping carrier news",
    "best USPS shipping alternatives",
    "DHL shipping delays Reddit",
    "how to ship large items",
    "Facebook parcel shipping tips",
    "FedEx express shipping cost",
    "UPS or DHL for international shipping",
    "cheapest way to send packages",
    "how to avoid customs delays",
    "Reddit shipping cost stories",
    "package missing updates",
    "shipping insurance claim Reddit",
    "Facebook shipping news",
    "best courier service for heavy packages",
    "Reddit shipping company comparisons",
    "cheapest international shipping options",
    "Reddit lost package tips",
    "FedEx or USPS for international",
    "cheapest way to ship internationally",
    "shipping delays 2023 news",
    "Reddit fastest shipping options",
    "how to track UPS package",
    "package delay Reddit posts",
    "shipping company problems Reddit",
    "Reddit shipping scam stories",
    "Yelp shipping carrier reviews",
    "best shipping app reviews",
    "shipping courier delay news",
    "shipping trends 2023 Reddit",
    "best way to ship overseas",
    "Reddit shipping scam warnings",
    "FedEx late delivery Reddit",
    "shipping news updates",
    "Yelp parcel delivery reviews",
    "international shipping struggles",
    "Reddit international package delays",
    "best online shipping calculator",
    "how to ship delicate items",
    "Facebook shipping community",
    "best shipping company 2023 Reddit",
    "USPS vs DHL shipping times",
    "Reddit lost package insurance",
    "Facebook shipping discussion group",
    "shipping industry 2023 trends",
    "FedEx vs UPS international",
    "cheapest way to ship clothing",
    "best way to ship furniture",
    "how to ship large furniture pieces",
    "Reddit package shipping reviews",
    "best shipping carrier for fragile items",
    "Reddit fast shipping tips",
    "why is my package not updating",
    "Yelp FedEx delivery complaints",
    "best courier service for businesses",
    "how to choose shipping insurance",
    "Yelp delivery service feedback",
    "how to handle customs delays",
    "Reddit reviews of FedEx shipping",
    "why is UPS delivery delayed",
    "best shipping service for small business",
    "shipping rate increases Reddit",
    "news on courier delays",
    "Reddit shipping rate tips",
    "Facebook delivery delays news",
    "shipping companies reviews 2023",
    "how to ship internationally Reddit",
    "cheapest express shipping Reddit",
    "best courier for fragile items",
    "news on USPS delays",
    "Reddit shipping delays complaints",
    "UPS vs FedEx shipping times Reddit",
    "Reddit cheapest shipping options",
    "Facebook shipping carrier reviews",
    "cheapest way to send parcel overseas",
    "Reddit customs delay stories",
    "shipping fragile items Reddit",
    "Reddit shipping carrier discussions",
    "shipping heavy packages Reddit",
    "best courier for international shipping",
    "how to file claim for lost package",
    "Reddit reviews of USPS shipping",
    "international package not delivered",
    "Reddit courier shipping reviews",
    "best shipping company for international",
    "news on parcel industry",
    "Reddit international delivery struggles",
    "Reddit best shipping options 2023",
    "Yelp courier reviews 2023",
    "how to ship valuables",
    "Facebook shipping tips group",
    "why is FedEx shipping so slow",
    "best courier service reviews 2023",
    "international package stuck in customs",
    "Reddit best way to ship internationally",
    "Reddit shipping service reviews",
    "FedEx shipping time delay Reddit",
    "DHL vs UPS international Reddit",
    "cheapest way to ship packages Reddit",
    "Reddit customs delay advice",
    "Facebook shipping complaints 2023",
    "Reddit fastest international shipping",
    "shipping services feedback Reddit",
    "how to reduce shipping times",
    "Yelp delivery reviews 2023",
    "best international shipping reviews",
    "Reddit international parcel shipping tips",
    "Reddit USPS delivery stories",
    "FedEx shipping delays Reddit",
    "Reddit courier reviews 2023",
    "shipping cost discussions Reddit",
    "Yelp shipping service reviews",
    "Reddit shipping price increases",
    "international shipping delays Reddit",
    "news on FedEx delays",
    "Reddit best courier services",
    "how to speed up international shipping",
    "Reddit cheap international shipping",
    "shipping delays updates",
    "best shipping companies for e-commerce",
    "FedEx vs UPS shipping Reddit",
    "Reddit tips on avoiding lost packages",
    "Yelp shipping delays 2023",
    "best courier services Reddit reviews",
    "international package not delivered Reddit",
    "Reddit fast shipping recommendations",
    "Facebook shipping feedback group",
    "Reddit DHL shipping reviews",
    "Reddit cheapest shipping options 2023",
    "shipping industry trends 2023",
    "Reddit shipping feedback 2023",
    "FedEx delays Reddit stories",
    "Facebook parcel delivery reviews",
    "Reddit best shipping options for small businesses",
    "best way to ship electronics Reddit",
    "Reddit UPS delivery complaints",
    "Yelp shipping service reviews 2023",
    "Reddit shipping service cost comparisons",
    "Facebook shipping group 2023",
    "shipping cost increases 2023 Reddit",
    "FedEx vs UPS delivery speed Reddit",
    "Reddit lost package stories",
    "Yelp shipping delay",
    "Facebook shipping complaints 2023",
    "Reddit fastest shipping options 2023",
    "how to track UPS package",
    "package delay Reddit posts",
    "shipping company problems Reddit",
]

search_queries = [
    "US parcel industry discussions forum",
    "parcel delivery discussions on Reddit",
    "shipping issues forums parcel industry",
    "USPS FedEx UPS delivery experiences forum",
    "Reddit discussions about lost packages",
    "customer complaints about USPS delivery",
    "FedEx delivery delays Reddit forum",
    "freight shipping discussions on forums",
    "parcel industry forums on delayed deliveries",
    "international parcel shipping issues forum",
    "YouTube videos transcribe parcel delivery issues",
    "YouTube review videos on FedEx service",
    "transcribe YouTube video on USPS parcel delays",
    "parcel shipping customer service reviews YouTube",
    "YouTube videos on shipping company comparisons",
    "How to track USPS packages YouTube tutorial",
    "transcribe YouTube reviews on parcel tracking",
    "parcel industry news RSS feed",
    "RSS feed on shipping carrier updates",
    "latest parcel industry innovations RSS feed",
    "global shipping issues news RSS feed",
    "RSS feed parcel shipping news",
    "new parcel tracking technologies RSS feed",
    "US parcel delivery updates news feed",
    "global supply chain RSS news feeds",
    "carrier information USPS FedEx UPS",
    "parcel carriers news and updates website",
    "scrape USPS carrier information from website",
    "UPS FedEx delivery service website scraping",
    "scrape delivery service issues from carriers website",
    "parcel shipping company information scraping",
    "parcel carriers information website scraping",
    "Yelp reviews parcel shipping services",
    "Yelp complaints on FedEx deliveries",
    "customer reviews on USPS parcel service Yelp",
    "Yelp reviews on international parcel shipments",
    "FedEx UPS delivery customer reviews Yelp",
    "Yelp complaints about lost packages",
    "shipping company reviews Yelp parcel industry",
    "Instagram posts parcel delivery issues",
    "scrape Instagram hashtags parcel delivery problems",
    "Instagram parcel shipping delays posts",
    "Instagram complaints about delivery services",
    "Instagram posts about USPS lost packages",
    "US parcel industry Instagram posts",
    "scrape Instagram posts on FedEx delivery",
    "Facebook groups discussions US parcel industry",
    "Facebook reviews of shipping carriers",
    "Facebook posts on delivery service problems",
    "Facebook complaints about parcel services",
    "scrape Facebook discussions on USPS delays",
    "customer reviews FedEx delivery on Facebook",
    "Facebook groups on UPS delivery issues",
    "Facebook discussions about delayed USPS shipments",
    "US parcel delivery experience posts Facebook",
    "Facebook group for international parcel shipping",
    "scrape Facebook posts on courier service complaints",
    "Reddit discussions on parcel tracking issues",
    "Reddit forums on global parcel delivery",
    "complaints about UPS service Reddit",
    "FedEx customer service issues Reddit forum",
    "USPS parcel delay Reddit posts",
    "scraping parcel industry discussions from Reddit",
    "Reddit lost package discussions",
    "international shipping delays Reddit forum",
    "customer issues with parcel carriers Reddit",
    "transcribe YouTube videos on USPS tracking",
    "transcribe YouTube reviews on UPS services",
    "parcel delivery tracking system YouTube tutorials",
    "YouTube reviews on parcel carriers FedEx UPS",
    "YouTube opinions on global shipping delays",
    "scrape YouTube comments on parcel delivery issues",
    "parcel delivery automation YouTube videos",
    "YouTube content on logistics and shipping updates",
    "global supply chain video content YouTube",
    "RSS feed for UPS shipping news",
    "scrape news RSS feed for parcel carrier updates",
    "parcel carrier technology RSS feed updates",
    "FedEx shipping news via RSS feed",
    "parcel delivery innovations RSS feed",
    "automated delivery services RSS news feed",
    "carrier contract agreements RSS feed",
    "scrape RSS news on shipping and logistics",
    "global logistics news updates RSS",
    "international shipping carrier news RSS feed",
    "parcel shipping service complaints Yelp",
    "scrape Yelp for UPS service reviews",
    "scrape Yelp reviews on FedEx delivery experiences",
    "customer reviews on USPS parcel services Yelp",
    "Yelp reviews for delayed packages",
    "FedEx parcel customer satisfaction reviews Yelp",
    "complaints about parcel carriers Yelp scraping",
    "Instagram posts about FedEx lost packages",
    "scrape Instagram posts about UPS shipping issues",
    "Instagram posts related to delayed parcel deliveries",
    "Instagram complaints about USPS services",
    "Instagram hashtags about parcel delivery problems",
    "scrape Instagram posts on international shipping",
    "Facebook reviews for USPS tracking services",
    "Facebook comments on parcel delivery delays",
    "Facebook discussions about FedEx package tracking",
    "scrape Facebook group posts on shipping issues",
    "Facebook feedback on UPS delivery"
]

category = [
    "shipping companies", # only US companies
]